apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    createdBy: gitlab-ce
  name: gitlab-ce-etc
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1014Mi
  storageClassName: local-hdd
