apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    createdBy: gitlab-ce
  name: gitlab-ce-data
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "49Gi"
  storageClassName: local-hdd
