apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    createdBy: gitlab-ce
  name: gitlab-ce-postgresql
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-hdd
