apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    createdBy: gitlab-ce
  name: gitlab-ce-redis-data
  namespace: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
  storageClassName: local-hdd
